#!/bin/sh
# Builds FreeType as a static archive for the browser-wasm platform.
#
# Emscripten ships a freetype port, but it cannot be used here: the .NET wasm
# SDK ships a frozen emscripten cache that must match its runtime pack, and
# building a port needs to write to that cache. So FreeType is built directly
# with the SDK's own compiler instead, which also keeps it binary-compatible
# with the runtime.
#
# The archive is named freetype6.a deliberately. .NET derives the P/Invoke
# module name from the file name, and FreeTypeFont.cs imports "freetype6".
#
# Usage: packaging/web/build-freetype.sh [version]

set -eu

VERSION="${1:-2.13.3}"
ENGINE_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")/../.." && pwd)"
BUILD_DIR="$ENGINE_DIR/OpenRA.Platforms.Web/native/freetype"
OUTPUT="$BUILD_DIR/freetype6.a"

EMSDK="${DOTNET_ROOT:-$HOME/.dotnet}/packs/Microsoft.NET.Runtime.Emscripten.3.1.56.Sdk.linux-x64"
EMCC="$(find "$EMSDK" -name emcc -type f 2>/dev/null | head -1)"
EMAR="$(find "$EMSDK" -name emar -type f 2>/dev/null | head -1)"

CACHE_PACK="${DOTNET_ROOT:-$HOME/.dotnet}/packs/Microsoft.NET.Runtime.Emscripten.3.1.56.Cache.linux-x64"
NODE_PACK="${DOTNET_ROOT:-$HOME/.dotnet}/packs/Microsoft.NET.Runtime.Emscripten.3.1.56.Node.linux-x64"

# The SDK's emscripten config reads its tool paths from these, and MSBuild
# normally sets them. Compiling only, never linking, so the frozen cache that
# blocks building emscripten's own freetype port is never written to.
TOOLS_DIR="$(dirname -- "$(dirname -- "$EMCC")")"
export DOTNET_EMSCRIPTEN_LLVM_ROOT="$TOOLS_DIR/bin"
export DOTNET_EMSCRIPTEN_BINARYEN_ROOT="$TOOLS_DIR"
export DOTNET_EMSCRIPTEN_NODE_JS="$(find "$NODE_PACK" -name node -type f 2>/dev/null | head -1)"
export EM_CACHE="$(find "$CACHE_PACK" -maxdepth 6 -type d -name cache 2>/dev/null | head -1)"

if [ -z "$EMCC" ] || [ -z "$EMAR" ]; then
	echo "error: could not find the SDK's emcc/emar under $EMSDK" >&2
	echo "       install the wasm-tools workload first: dotnet workload install wasm-tools" >&2
	exit 1
fi

if [ -f "$OUTPUT" ]; then
	echo "$OUTPUT already exists; delete it to rebuild."
	exit 0
fi

mkdir -p "$BUILD_DIR"
SRC="$BUILD_DIR/freetype-$VERSION"

if [ ! -d "$SRC" ]; then
	echo "Fetching FreeType $VERSION..."
	curl -fsSL "https://download.savannah.gnu.org/releases/freetype/freetype-$VERSION.tar.gz" \
		| tar xz -C "$BUILD_DIR"
fi

# Only the modules OpenRA needs: TrueType parsing plus the smooth (anti-aliased)
# rasterizer. The autofitter, CFF/Type1 and bitmap font backends are left out.
# The SJLJ and exception flags must match how the .NET runtime is built: the
# smooth rasterizer uses setjmp, and mixing longjmp implementations fails to
# link.
#
# ftmm is not optional despite being unused: sfnt references it for variable
# fonts. WOFF decompression is stubbed in webgl_shim.c instead of building the
# gzip module, which needs setjmp and will not link against the runtime's
# compiler-rt. OpenRA only loads plain TrueType fonts.
MODULES="
src/base/ftbase.c src/base/ftbitmap.c src/base/ftdebug.c src/base/ftglyph.c
src/base/ftinit.c src/base/ftsystem.c src/base/ftmm.c
src/truetype/truetype.c src/sfnt/sfnt.c src/psnames/psnames.c
src/smooth/smooth.c
"

# ftinit.c registers every module in FreeType's default list, which would pull in
# drivers that are not built here. Restrict it to the ones above.
cat > "$BUILD_DIR/ftmodule-openra.h" <<'HEADER'
/* Generated by packaging/web/build-freetype.sh - only the modules OpenRA needs. */
FT_USE_MODULE( FT_Driver_ClassRec, tt_driver_class )
FT_USE_MODULE( FT_Module_Class, sfnt_module_class )
FT_USE_MODULE( FT_Module_Class, psnames_module_class )
FT_USE_MODULE( FT_Renderer_Class, ft_smooth_renderer_class )
HEADER

echo "Building with $EMCC..."
OBJECTS=""
for source in $MODULES; do
	object="$BUILD_DIR/$(basename "$source" .c).o"
	"$EMCC" -c "$SRC/$source" -o "$object" \
		-O2 -DFT2_BUILD_LIBRARY -I"$SRC/include" -I"$BUILD_DIR" \
		-DFT_CONFIG_MODULES_H='<ftmodule-openra.h>' \
		-sSUPPORT_LONGJMP=wasm -mllvm -wasm-enable-sjlj -fwasm-exceptions \
		-Wno-unused-command-line-argument
	OBJECTS="$OBJECTS $object"
done

# shellcheck disable=SC2086
"$EMAR" rcs "$OUTPUT" $OBJECTS
rm -f $OBJECTS

echo "Built $OUTPUT"
